help: 
db ' Mod 1.0 - 1996            Written by Kevin Drapel aka Dake',13,10 
db 13,10 
db '     Mod is an utility who toggle between text modes when you use the DOS',13,10  
db '                     (See mod10.doc for more information)',13,10 
db 13,10                           
db ' Usage : MOD [choice]            Ex: MOD /1' ,13,10 
db 13,10 
db 13,10 
db ' 1: 40x25 B/W                    5: 132x60 (vesa only)',13,10 
db ' 2: 40x25 16 colors              6: 132x50 (vesa only)',13,10 
db ' 3: 80x30 16 colors              7: 132x43 (vesa only)',13,10 
db ' 4: 80x50 16 colors              8: 80x25 (standard mode)',13,10 
db ' 9: White backround',13,10 
db 13,10         
db '$'
